id = "gt"
name = "GT"
description = "Graph Text (.gt) syntax highlighting"
version = "0.1.0"
schema_version = 1
authors = ["marsgpl"]
repository = "https://github.com/marsgpl/zed-gt-extension"

[grammars.gt]
repository = "https://github.com/marsgpl/zed-gt-extension"
commit = "2770ac0b9846ac97c1dc6066caec54527bf7bf66"
