id = "gt"
name = "GT"
description = "Graph Text (.gt) syntax highlighting"
version = "0.1.0"
schema_version = 1
authors = ["marsgpl"]
repository = "https://github.com/marsgpl/zed-gt-extension"

[grammars.gt]
repository = "https://github.com/marsgpl/zed-gt-extension"
commit = "bc4a1ef203d3ee1c605c860a817d2f85108c5f26"
