/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 23
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 19
#define ALIAS_COUNT 0
#define TOKEN_COUNT 10
#define EXTERNAL_TOKEN_COUNT 4
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 7
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  aux_sym_node_line_token1 = 1,
  anon_sym_ = 2,
  anon_sym_COLON = 3,
  anon_sym_SPACE = 4,
  aux_sym_node_name_token1 = 5,
  sym__node_line_marker = 6,
  sym__edge_line_marker = 7,
  sym_error_line = 8,
  sym_blank_line = 9,
  sym_source_file = 10,
  sym__line = 11,
  sym_node_line = 12,
  sym_edge_line = 13,
  sym_node_name = 14,
  sym_edge_name = 15,
  sym_target_name = 16,
  aux_sym_source_file_repeat1 = 17,
  aux_sym_source_file_repeat2 = 18,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [aux_sym_node_line_token1] = "node_line_token1",
  [anon_sym_] = "    ",
  [anon_sym_COLON] = ":",
  [anon_sym_SPACE] = " ",
  [aux_sym_node_name_token1] = "node_name_token1",
  [sym__node_line_marker] = "_node_line_marker",
  [sym__edge_line_marker] = "_edge_line_marker",
  [sym_error_line] = "error_line",
  [sym_blank_line] = "blank_line",
  [sym_source_file] = "source_file",
  [sym__line] = "_line",
  [sym_node_line] = "node_line",
  [sym_edge_line] = "edge_line",
  [sym_node_name] = "node_name",
  [sym_edge_name] = "edge_name",
  [sym_target_name] = "target_name",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_source_file_repeat2] = "source_file_repeat2",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [aux_sym_node_line_token1] = aux_sym_node_line_token1,
  [anon_sym_] = anon_sym_,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_SPACE] = anon_sym_SPACE,
  [aux_sym_node_name_token1] = aux_sym_node_name_token1,
  [sym__node_line_marker] = sym__node_line_marker,
  [sym__edge_line_marker] = sym__edge_line_marker,
  [sym_error_line] = sym_error_line,
  [sym_blank_line] = sym_blank_line,
  [sym_source_file] = sym_source_file,
  [sym__line] = sym__line,
  [sym_node_line] = sym_node_line,
  [sym_edge_line] = sym_edge_line,
  [sym_node_name] = sym_node_name,
  [sym_edge_name] = sym_edge_name,
  [sym_target_name] = sym_target_name,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_source_file_repeat2] = aux_sym_source_file_repeat2,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_node_line_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SPACE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_node_name_token1] = {
    .visible = false,
    .named = false,
  },
  [sym__node_line_marker] = {
    .visible = false,
    .named = true,
  },
  [sym__edge_line_marker] = {
    .visible = false,
    .named = true,
  },
  [sym_error_line] = {
    .visible = true,
    .named = true,
  },
  [sym_blank_line] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__line] = {
    .visible = false,
    .named = true,
  },
  [sym_node_line] = {
    .visible = true,
    .named = true,
  },
  [sym_edge_line] = {
    .visible = true,
    .named = true,
  },
  [sym_node_name] = {
    .visible = true,
    .named = true,
  },
  [sym_edge_name] = {
    .visible = true,
    .named = true,
  },
  [sym_target_name] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_source_file_repeat2] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(7);
      if (lookahead == '\n') ADVANCE(8);
      if (lookahead == ' ') ADVANCE(12);
      if (lookahead == ':') ADVANCE(10);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(13);
      END_STATE();
    case 1:
      if (lookahead == ' ') ADVANCE(4);
      END_STATE();
    case 2:
      if (lookahead == ' ') ADVANCE(9);
      END_STATE();
    case 3:
      if (lookahead == ' ') ADVANCE(11);
      END_STATE();
    case 4:
      if (lookahead == ' ') ADVANCE(2);
      END_STATE();
    case 5:
      if (lookahead == ' ') ADVANCE(1);
      END_STATE();
    case 6:
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(13);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(aux_sym_node_line_token1);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_SPACE);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_SPACE);
      if (lookahead == ' ') ADVANCE(4);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(aux_sym_node_name_token1);
      if (lookahead == ' ') ADVANCE(6);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(13);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 0, .external_lex_state = 2},
  [2] = {.lex_state = 0, .external_lex_state = 1},
  [3] = {.lex_state = 0, .external_lex_state = 1},
  [4] = {.lex_state = 0, .external_lex_state = 1},
  [5] = {.lex_state = 0, .external_lex_state = 1},
  [6] = {.lex_state = 0, .external_lex_state = 1},
  [7] = {.lex_state = 0, .external_lex_state = 2},
  [8] = {.lex_state = 0, .external_lex_state = 1},
  [9] = {.lex_state = 0, .external_lex_state = 2},
  [10] = {.lex_state = 0, .external_lex_state = 1},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 5},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 3},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [aux_sym_node_line_token1] = ACTIONS(1),
    [anon_sym_] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_SPACE] = ACTIONS(1),
    [aux_sym_node_name_token1] = ACTIONS(1),
    [sym__node_line_marker] = ACTIONS(1),
    [sym__edge_line_marker] = ACTIONS(1),
    [sym_error_line] = ACTIONS(1),
    [sym_blank_line] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(14),
    [sym_node_line] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(7),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym__node_line_marker] = ACTIONS(5),
    [sym_error_line] = ACTIONS(7),
    [sym_blank_line] = ACTIONS(7),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 5,
    ACTIONS(5), 1,
      sym__node_line_marker,
    ACTIONS(9), 1,
      ts_builtin_sym_end,
    ACTIONS(11), 1,
      sym__edge_line_marker,
    ACTIONS(13), 2,
      sym_error_line,
      sym_blank_line,
    STATE(3), 4,
      sym__line,
      sym_node_line,
      sym_edge_line,
      aux_sym_source_file_repeat2,
  [20] = 5,
    ACTIONS(5), 1,
      sym__node_line_marker,
    ACTIONS(11), 1,
      sym__edge_line_marker,
    ACTIONS(15), 1,
      ts_builtin_sym_end,
    ACTIONS(17), 2,
      sym_error_line,
      sym_blank_line,
    STATE(5), 4,
      sym__line,
      sym_node_line,
      sym_edge_line,
      aux_sym_source_file_repeat2,
  [40] = 5,
    ACTIONS(5), 1,
      sym__node_line_marker,
    ACTIONS(11), 1,
      sym__edge_line_marker,
    ACTIONS(15), 1,
      ts_builtin_sym_end,
    ACTIONS(19), 2,
      sym_error_line,
      sym_blank_line,
    STATE(6), 4,
      sym__line,
      sym_node_line,
      sym_edge_line,
      aux_sym_source_file_repeat2,
  [60] = 5,
    ACTIONS(21), 1,
      ts_builtin_sym_end,
    ACTIONS(23), 1,
      sym__node_line_marker,
    ACTIONS(26), 1,
      sym__edge_line_marker,
    ACTIONS(29), 2,
      sym_error_line,
      sym_blank_line,
    STATE(5), 4,
      sym__line,
      sym_node_line,
      sym_edge_line,
      aux_sym_source_file_repeat2,
  [80] = 5,
    ACTIONS(5), 1,
      sym__node_line_marker,
    ACTIONS(11), 1,
      sym__edge_line_marker,
    ACTIONS(32), 1,
      ts_builtin_sym_end,
    ACTIONS(17), 2,
      sym_error_line,
      sym_blank_line,
    STATE(5), 4,
      sym__line,
      sym_node_line,
      sym_edge_line,
      aux_sym_source_file_repeat2,
  [100] = 5,
    ACTIONS(5), 1,
      sym__node_line_marker,
    ACTIONS(9), 1,
      ts_builtin_sym_end,
    STATE(4), 1,
      sym_node_line,
    STATE(9), 1,
      aux_sym_source_file_repeat1,
    ACTIONS(34), 2,
      sym_error_line,
      sym_blank_line,
  [117] = 1,
    ACTIONS(36), 5,
      sym__node_line_marker,
      sym__edge_line_marker,
      sym_error_line,
      sym_blank_line,
      ts_builtin_sym_end,
  [125] = 3,
    STATE(9), 1,
      aux_sym_source_file_repeat1,
    ACTIONS(38), 2,
      sym__node_line_marker,
      ts_builtin_sym_end,
    ACTIONS(40), 2,
      sym_error_line,
      sym_blank_line,
  [137] = 1,
    ACTIONS(43), 5,
      sym__node_line_marker,
      sym__edge_line_marker,
      sym_error_line,
      sym_blank_line,
      ts_builtin_sym_end,
  [145] = 2,
    ACTIONS(45), 1,
      aux_sym_node_name_token1,
    STATE(16), 1,
      sym_node_name,
  [152] = 2,
    ACTIONS(47), 1,
      aux_sym_node_name_token1,
    STATE(18), 1,
      sym_edge_name,
  [159] = 2,
    ACTIONS(49), 1,
      aux_sym_node_name_token1,
    STATE(22), 1,
      sym_target_name,
  [166] = 1,
    ACTIONS(51), 1,
      ts_builtin_sym_end,
  [170] = 1,
    ACTIONS(53), 1,
      aux_sym_node_line_token1,
  [174] = 1,
    ACTIONS(55), 1,
      aux_sym_node_line_token1,
  [178] = 1,
    ACTIONS(57), 1,
      anon_sym_,
  [182] = 1,
    ACTIONS(59), 1,
      anon_sym_COLON,
  [186] = 1,
    ACTIONS(61), 1,
      anon_sym_COLON,
  [190] = 1,
    ACTIONS(63), 1,
      anon_sym_SPACE,
  [194] = 1,
    ACTIONS(65), 1,
      aux_sym_node_line_token1,
  [198] = 1,
    ACTIONS(67), 1,
      aux_sym_node_line_token1,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 20,
  [SMALL_STATE(4)] = 40,
  [SMALL_STATE(5)] = 60,
  [SMALL_STATE(6)] = 80,
  [SMALL_STATE(7)] = 100,
  [SMALL_STATE(8)] = 117,
  [SMALL_STATE(9)] = 125,
  [SMALL_STATE(10)] = 137,
  [SMALL_STATE(11)] = 145,
  [SMALL_STATE(12)] = 152,
  [SMALL_STATE(13)] = 159,
  [SMALL_STATE(14)] = 166,
  [SMALL_STATE(15)] = 170,
  [SMALL_STATE(16)] = 174,
  [SMALL_STATE(17)] = 178,
  [SMALL_STATE(18)] = 182,
  [SMALL_STATE(19)] = 186,
  [SMALL_STATE(20)] = 190,
  [SMALL_STATE(21)] = 194,
  [SMALL_STATE(22)] = 198,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [9] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0),
  [23] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0), SHIFT_REPEAT(11),
  [26] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0), SHIFT_REPEAT(17),
  [29] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0), SHIFT_REPEAT(5),
  [32] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 3, 0, 0),
  [34] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [36] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_node_line, 3, 0, 0),
  [38] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [40] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_edge_line, 7, 0, 0),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [51] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_node_name, 1, 0, 0),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_edge_name, 1, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_target_name, 1, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token__node_line_marker = 0,
  ts_external_token__edge_line_marker = 1,
  ts_external_token_error_line = 2,
  ts_external_token_blank_line = 3,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__node_line_marker] = sym__node_line_marker,
  [ts_external_token__edge_line_marker] = sym__edge_line_marker,
  [ts_external_token_error_line] = sym_error_line,
  [ts_external_token_blank_line] = sym_blank_line,
};

static const bool ts_external_scanner_states[3][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__node_line_marker] = true,
    [ts_external_token__edge_line_marker] = true,
    [ts_external_token_error_line] = true,
    [ts_external_token_blank_line] = true,
  },
  [2] = {
    [ts_external_token__node_line_marker] = true,
    [ts_external_token_error_line] = true,
    [ts_external_token_blank_line] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_gt_external_scanner_create(void);
void tree_sitter_gt_external_scanner_destroy(void *);
bool tree_sitter_gt_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_gt_external_scanner_serialize(void *, char *);
void tree_sitter_gt_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_gt(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_gt_external_scanner_create,
      tree_sitter_gt_external_scanner_destroy,
      tree_sitter_gt_external_scanner_scan,
      tree_sitter_gt_external_scanner_serialize,
      tree_sitter_gt_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
    .name = "gt",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
